---
collections:
  - ansible.posix
  - ansible.netcommon
  - community.general
  - community.postgresql
  - community.grafana
  - netbox.netbox
  - netcho.opennebula
  - name: prometheus.prometheus
    source: https://github.com/prometheus-community/ansible.git
    type: git
