---
collections:
  - ansible.posix
  - ansible.netcommon
  - ansible.utils
  - community.general
  - community.grafana
  - community.mysql
  - netbox.netbox
  - name: netcho.opennebula
    type: git
    source: https://github.com/netcho/opennebula-collection
  - prometheus.prometheus

