---
collections:
  - ansible.posix
  - ansible.netcommon
  - ansible.utils
  - community.general
  - community.grafana
  - netbox.netbox
  - src: https://github.com/netcho/opennebula-collection
    name: netcho.opennebula

