apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: internal
  namespace: internal-monitoring
spec:
  replicas: 1
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: internal-monitoring
        port: web
  serviceMonitorSelector:
    matchLabels:
      storpool.com/env: production
  serviceMonitorNamespaceSelector:
    matchExpressions:
      - key: storpool.com/kind
        operator: In
        values:
          - service
          - system
  podMonitorSelector:
    matchLabels:
      storpool.com/env: production
  podMonitorNamespaceSelector:
    matchExpressions:
      - key: storpool.com/kind
        operator: In
        values:
          - service
          - system
  scrapeConfigSelector:
    matchLabels:
      storpool.com/env: production
  scrapeConfigNamespaceSelector:
    matchExpressions:
      - key: storpool.com/kind
        operator: In
        values:
          - service
          - system
  ruleSelector:
    matchLabels:
      storpool.com/env: production
  ruleNamespaceSelector:
    matchExpressions:
      - key: storpool.com/kind
        operator: In
        values:
          - service
          - system
  scrapeInterval: 3s
  retention: 12h
  remoteWrite:
    - name: VictoriaMetrics
      url: http://vmsingle-metrics:8429/api/v1/write
      queueConfig:
        capacity: 20000
        maxShards: 30
        maxSamplesPerSend: 10000
      writeRelabelConfigs:
        - separator: ;
          regex: prometheus_replica
          replacement: $1
          action: labeldrop
  resources:
    requests:
      memory: 400Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: storpool-nvme
        resources:
          requests:
            storage: 40Gi
  serviceAccountName: prometheus
  securityContext:
    fsGroup: 65534
