apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: metrics
  namespace: internal-monitoring
spec:
  retentionPeriod: '12'
  disableSelfServiceScrape: false
  extraArgs:
    dedup.minScrapeInterval: '3s'
    search.maxConcurrentRequests: '16'
  resources:
    limits:
      cpu: '4'
      memory: 5000Mi
  storage:
    accessModes:
      - ReadWriteOnce
    volumeName: pvc-3c81dcaa-efe8-4f21-9aca-28066a874a92
