---
- name: Installing node-exporter
  hosts: moonstone_monitor
  become_method: sudo
  pre_tasks:
    - name: Collect running services
      service_facts:
  roles:
    - name: cloudalchemy.node_exporter
      become: true
  post_tasks:
    - name: Enable node exporter port on firewall
      become: true
      ansible.posix.firewalld:
        port: "{{ node_exporter_web_listen_port }}/tcp"
        state: enabled
        permanent: true
        immediate: true
      when:
        - ansible_os_family == 'RedHat'
        - ansible_facts.services['firewalld'] is defined
        - ansible_facts.services['firewalld'].state == 'running'
  vars_files: vars/node-exporter.yaml

- name: Updating Prometheus static targets
  hosts: monitoring-stack
  become_method: sudo
  roles:
    - name: generate-static-targets
      vars:
        file_sd_template_path: "{{ playbook_dir + '/prometheus/job-templates/*.yaml.j2' }}"
