- name: Deploying monitoring stack
  hosts: localhost
  tasks:
    - name: Adding Prometheus Helm chart
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts

    - name: Updating the repository cache
      kubernetes.core.helm:
        name: dummy
        namespace: kube-system
        state: absent
        update_repo_cache: true

    - name: Deploying the Prometheus Helm chart
      kubernetes.core.helm:
        release_name: prometheus-internal
        release_values: {{ lookup("template", "prometheus_values.yaml.j2") | from_yaml }}
        release_namespace: internal-monitoring
        chart_ref: prometheus-community/prometheus
        create_namespace: yes
        wait: yes
