---
- name: Installing TimescaleDB
  hosts: monitoring-stack
  become_method: sudo
  roles:
    - name: timescale_db
      become: true

- name: Installing monitoring stack
  hosts: monitoring-stack
  become_method: sudo
  pre_tasks:
    - name: Creating Prometheus file service discovery directory
      become: true
      file:
        path: /monitoring/prometheus_file_sd/
        state: directory
    - name: Generating Promscale PostgreSQL user password
      set_fact:
        promscale_postgres_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"
    - name: Debugging alertmanager routes
      debug:
        var: alertmanager_route
        verbosity: 2
  roles:
    - name: create-postgresql-database
      become: true
    - name: promscale
      become: true
    - name: cloudalchemy.snmp-exporter
      become: true
    - name: cloudalchemy.alertmanager
      become: true
    - name: cloudalchemy.prometheus
      become: true
  vars_files:
    - vars/prometheus.yaml
    - vars/alertmanager.yaml
    - vars/grafana.yaml

- name: Installing Grafana
  hosts: monitoring-stack
  become_method: sudo
  pre_tasks:
    - name: Generating Grafana PostgreSQL user password
      set_fact:
        grafana_database_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"
    - name: Generating Grafana admin credentials
      set_fact:
        grafana_security:
          admin_user: admin
          admin_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"
  roles:
    - name: create-postgresql-database
      become: true
    - name: cloudalchemy.grafana
      become: true
  vars_files: vars/grafana.yaml
