---
- name: Installing node-exporter
  hosts: moonstone_monitor
  become_method: sudo
  roles:
    - name: cloudalchemy.node_exporter
      become: true
  post_tasks:
    - name: Enable node exporter port on firewall
      ansible.posix.firewalld:
        port: "{{ node_exporter_web_listen_port }}/tcp"
        state: enabled
        permanent: true
        immediate: true
  vars_files: vars/node-exporter.yaml

- name: Updating Prometheus static targets
  hosts: monitoring-stack
  become_method: sudo
  roles:
    - generate-static-targets
