---
- name: Installing node-exporter
  hosts: moonstone_monitor
  become_method: sudo
  roles:
    - name: cloudalchemy.node_exporter
      become: true
  vars_files: vars/node-exporter.yaml

- name: Regenerating Prometheus static targets
  hosts: prometheusA
  become_method: sudo
  roles:
    - generate-static-targets
