---
- name: Installing node-exporter
  hosts: monitor_nodes
  become_method: sudo
  pre_tasks:
    - name: Collect running services
      service_facts:
  roles:
    - name: cloudalchemy.node_exporter
      become: true
  post_tasks:
    - name: Configuring firewall
      import_tasks: tasks/node-exporter-firewall.yaml
    - name: Installing debug tools
      import_tasks: tasks/install-debug-tools.yaml
  vars_files: vars/node-exporter.yaml

- name: Updating Prometheus static targets
  hosts: monitoring-stack
  become_method: sudo
  roles:
    - name: generate-static-targets
      vars:
        file_sd_template_path: "{{ playbook_dir + '/prometheus/job-templates/*.yaml.j2' }}"
