---
- name: Deploying Prometheus
  hosts: prometheus
  become_method: sudo
  pre_tasks:
    - name: Creating Prometheus file service discovery directory
      become: true
      file:
        path: /monitoring/file_sd/
        state: directory
  roles:
    - name: cloudalchemy.prometheus
      become: true
  vars_files: vars/prometheus.yaml
