---
- name: Installing TimescaleDB
  hosts: monitoring-stack
  become_method: sudo
  roles:
    - name: timescale_db
      become: true

- name: Installing Promscale and Prometheus
  hosts: monitoring-stack
  become_method: sudo
  pre_tasks:
    - name: Creating Prometheus file service discovery directory
      become: true
      file:
        path: /monitoring/file_sd/
        state: directory
  roles:
    - name: promscale
      become: true
    - name: cloudalchemy.prometheus
      become: true
  vars_files: vars/prometheus.yaml
