- name: Installing Grafana
  hosts: monitoring-stack
  become_method: sudo
  pre_tasks:
    - name: Generating Grafana PostgreSQL user password
      set_fact:
        grafana_database_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"
    - name: Generating Grafana admin credentials
      set_fact:
        grafana_security:
          admin_user: admin
          admin_password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"
    - name: Creating Grafana database
      import_tasks: tasks/create-granafa-database.yaml
  roles:
    - name: cloudalchemy.grafana
      become: true
  vars_files: vars/grafana.yaml

- name: Installing Karma
  hosts: monitoring-stack
  become_method: sudo
  roles:
    - name: storpool.karma
      become: true
  vars_files:
    - vars/alertmanager.yaml
    - vars/karma.yaml
