---
- name: Installing node-exporter
  hosts: deploy_node_exporter
  become_method: sudo
  pre_tasks:
    - name: Collect running services
      service_facts:
  roles:
    - name: infrastructure_host
      become: true
    - name: cloudalchemy.node_exporter
      become: true
  post_tasks:
    - name: Configuring firewall
      become: true
      import_tasks: tasks/node-exporter-firewall.yaml
  vars_files: vars/node-exporter.yaml
  ansible_python_interpreter: /usr/bin/python3
