---
- name: Configuring common settings
  hosts: deploy_node_exporter
  become_method: sudo
  roles:
    - name: infrastructure_host
      become: true
  vars_files:
    - vars/infrastructure.yaml

- name: Installing node-exporter
  hosts: deploy_node_exporter
  become_method: sudo
  pre_tasks:
    - name: Collect running services
      service_facts:
    - name: Setting python interpreter version to use
      set_fact:
        ansible_python_interpreter: "{{ '/usr/bin/' + redhat_python_version_map['redhat_' + ansible_distribution_major_version] if ansible_os_family == 'RedHat' else 'auto' }}"
  roles:
    - name: prometheus.prometheus.node_exporter
      become: true
  tasks:
    - name: Creating node_exporter drop-in directory
      become: true
      file:
        path: /etc/systemd/system/node_exporter.service.d/
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Creating node_exporter oom score systemd drop-in
      become: true
      copy:
        dest: /etc/systemd/system/node_exporter.service.d/10-oom-score.conf
        src: files/node-exporter-oom-score.conf
        owner: root
        group: root
        mode: 0644
      notify: restart node_exporter
  post_tasks:
    - name: Configuring firewall
      become: true
      import_tasks: tasks/node-exporter-firewall.yaml
  vars_files:
    - vars/infrastructure.yaml
    - vars/node-exporter.yaml
