- name: Deploying the ipmi-exporter on baremetal hosts
  hosts: baremetal_machines,!sp-mgmt
  roles:
    - name: prometheus.prometheus.ipmi_exporter
      become: true
  vars_files:
    - vars/ipmi-exporter.yaml
