---
- name: Installing node-exporter
  hosts: deploy_node_exporter
  become_method: sudo
  pre_tasks:
    - name: Collect running services
      service_facts:
  roles:
    - name: cloudalchemy.node_exporter
      become: true
  post_tasks:
    - name: Configuring firewall
      become: true
      import_tasks: tasks/node-exporter-firewall.yaml
    - name: Installing debug tools
      become: true
      import_tasks: tasks/install-debug-tools.yaml
  vars_files: vars/node-exporter.yaml
