---
- name: Configuring common settings
  hosts: deploy_node_exporter
  become_method: sudo
  roles:
    - name: infrastructure_host
      become: true

- name: Installing node-exporter
  hosts: deploy_node_exporter
  become_method: sudo
  pre_tasks:
    - name: Collect running services
      service_facts:
    - name: Setting python interpreter version to use
      set_fact:
        ansible_python_interpreter: "{{ '/usr/bin/' + redhat_python_version_map['redhat_' + ansible_distribution_major_version] if ansible_os_family == 'RedHat' else 'auto' }}"
  roles:
    - name: cloudalchemy.node_exporter
      become: true
  post_tasks:
    - name: Configuring firewall
      become: true
      import_tasks: tasks/node-exporter-firewall.yaml
  vars_files: vars/node-exporter.yaml
