---
- name: Deploy postgres exporter
  hosts: postgresql_hosts
  become: yes
  pre_tasks:
    - name: Creating exporter user
      community.postgresql.postgresql_user:
        name: "{{ postgres_exporter_system_user }}"
    - name: Allowing the exporter user to connect to the postgres database
      community.postgresql.postgresql_privs:
        db: postgres
        privs: CONNECT
        type: database
        roles: "{{ postgres_exporter_system_user }}"
    - name: Granting monitoring permissions to the exporter user
      community.postgresql.postgresql_privs:
        db: postgres
        privs: pg_monitor
        roles: "{{ postgres_exporter_system_user }}"
  roles:
    - prometheus.prometheus.postgres_exporter
