- name: Deploying the ipmi-exporter on baremetal hosts
  hosts: baremetal_machines,!sp-mgmt
  roles:
    - name: prometheus.prometheus.ipmi_exporter
      become: true
      vars:
        ipmi_exporter_modules: "{{ ipmi_exporter_available_modules }}"
  vars_files:
    - vars/ipmi-exporter.yaml
