---
# tasks file for infrastructure_host
- name: Updating apt local cache
  apt:
    update_cache: true
  when: ansible_pkg_mgr == "apt"
  ignore_errors: true

- name: Installing python on RHEL-like distros
  package:
    name: "{{ (ansible_distribution_major_version | int >= 8) | ternary('python3', 'python2') }}"
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Installing debug tools
  package:
    name:
      - strace
      - ltrace
      - vim
      - mtr
    state: present