- name: Updating apt local cache
  apt:
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Installing debug tools
  package:
    name:
      - strace
      - ltrace
      - vim
      - mtr
    state: present
