- name: Enable node exporter port on firewalld
  ansible.posix.firewalld:
    port: "{{ node_exporter_web_listen_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  when:
    - ansible_facts.services['firewalld'] is defined
    - ansible_facts.services['firewalld'].state == 'running'