- name: Configuring firewalld
  block:
    - ansible.posix.firewalld:
        port: "{{ node_exporter_web_listen_port }}/tcp"
        state: enabled
        permanent: true
    - service:
        name: firewalld
        state: reloaded
  when:
    - "'firewalld.service' in ansible_facts.services"
    - "ansible_facts.services['firewalld.service'].state == 'running'"