- name: Configuring firewalld
  block:
    - name: Enabling node-exporter port
      ansible.posix.firewalld:
        port: "{{ node_exporter_web_listen_port }}/tcp"
        state: enabled
        permanent: true
      register: port_enable
    - name: Reloading firewalld
      service:
        name: firewalld
        state: reloaded
      when: port_enable.changed
  when:
    - "'firewalld.service' in ansible_facts.services"
    - "ansible_facts.services['firewalld.service'].state == 'running'"