- name: Enable node exporter port on firewalld
  ansible.posix.firewalld:
    port: "{{ node_exporter_web_listen_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  when:
    - "firewalld" in ansible_facts.services
    - ansible_facts.services["firewalld"].state == "running"