- name: Patching snmp.yml to support community authentication
  blockinfile:
    path: /etc/snmp_exporter/snmp.yml
    insertafter: '{{ mib_name }}:'
    block: |2
        auth:
          community: internalmon
        timeout: 15s
  loop:
    - if_mib
    - apcups
  loop_control:
    loop_var: mib_name

- name: Restarting snmp_exporter
  service:
    name: snmp_exporter
    state: restarted
