- name: Patching snmp.yml to support community authentication
  blockinfile:
    path: /etc/snmp_exporter/snmp.yml
    insertafter: '{{ mib_name }}:'
    block: |2
        auth:
          community: internalmon
        timeout: 15s
    marker: '# {mark} Patched authorization for mib {{ mib_name }}'
  loop:
    - apcups
    - if_mib
  loop_control:
    loop_var: mib_name
  notify:
    - restart snmp exporter
