- name: Installing PGDG repository
  dnf:
    name:
      - "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: installed
    disable_gpg_check: true

- name: Adding TimescaleDB repository
  yum_repository:
    name: timescale_timescaledb
    baseurl: "https://packagecloud.io/timescale/timescaledb/el/{{ ansible_distribution_major_version }}/$basearch"
    description: "TimescaleDB repo"
    repo_gpgcheck: true
    gpgcheck: false
    enabled: true
    gpgkey: https://packagecloud.io/timescale/timescaledb/gpgkey
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300

- name: Disabling built-in PostgreSQL module
  copy:
    dest: /etc/dnf/modules.d/postgresql.module
    content: |
      [postgresql]
      name=postgresql
      stream=
      profiles=
      state=disabled

- name: Installing TimescaleDB
  dnf:
    name:
      - timescaledb-2-postgresql-13
      - libpq5-devel
    state: latest

- name: Initializing PostgreSQL database
  shell:
    cmd: /usr/pgsql-13/bin/postgresql-13-setup initdb
    creates: /var/lib/pgsql/13/data/postgresql.conf
