- name: Installing dependencies
  apt:
    name:
      - postgresql-common
      - gnupg
      - wget
    state: present

- name: Adding PostgreSQL third-party repo
  shell:
    cmd: YES=yes /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
    creates: /etc/apt/sources.list.d/pgdg.list

- name: Adding TimescaleDB third-party repo key
  shell:
    cmd: wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | gpg --dearmor -o /usr/share/keyrings/timescale.keyring
    creates: /usr/share/keyrings/timescale.keyring

- name: Adding TimescaleDB third-party repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/timescale.keyring] https://packagecloud.io/timescale/timescaledb/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"

- name: Installing TimescaleDB
  apt:
    name: timescaledb-2-postgresql-13
    state: present
