- name: Installing postgresql-common package
  apt:
    name: postgresql-common
    state: present

- name: Adding PostgreSQL third-party repo
  shell: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh

- name: Adding TimescaleDB third-party repo key
  shell: wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | gpg --dearmor -o /usr/share/keyrings/timescale.keyring

- name: Adding TimescaleDB third-party repo
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/timescale.keyring] https://packagecloud.io/timescale/timescaledb/ubuntu/ {{ ansible_distribution_release }} main"

- name: Installing TimescaleDB
  apt:
    name: timescale2-postgresql-13
    state: present
