---
# tasks file for timescale_db
- name: Installing TimescaleDB
  include_tasks: "install-{{ ansible_pkg_mgr }}.yaml"

- name: Checking if TimescaleDB shared library has been added to postgresql.conf
  shell: grep "shared_preload_libraries = 'timescaledb'" /etc/postgresql/13/main/postgresql.conf | wc -l
  register: is_timescale_loaded
  changed_when: is_timescale_loaded.stdout == "0"

- name: Tuning PostgreSQL for TimescaleDB
  command:
    argv:
      - timescaledb-tune
      - --quiet
      - --yes
  notify: Restart PostgreSQL
  when: is_timescale_loaded.stdout == "0"
