---
# tasks file for timescale_db
- name: Installing TimescaleDB
  include_tasks: "install-{{ ansible_pkg_mgr }}.yaml"

- name: Tuning PostgreSQL for TimescaleDB
  command:
    argv:
      - timescaledb-tune
      - --quiet
      - --yes
  notify: Restart PostgreSQL