---
# tasks file for timescale_db
- name: Installing TimescaleDB packages
  include_tasks: "install-{{ ansible_pkg_mgr }}.yaml"

- name: Checking if TimescaleDB shared library has been added to postgresql.conf
  shell: "grep \"shared_preload_libraries = 'timescaledb'\" {{ lookup('vars', 'postgre_config_file_' + ansible_distribution.lower()) }} | wc -l"
  register: is_timescale_loaded
  changed_when: is_timescale_loaded.stdout == "0"

- name: Tuning PostgreSQL for TimescaleDB
  command:
    argv:
      - timescaledb-tune
      - "--pg_config {{ '/usr/pgsql-13/bin/pg_config' if ansible_os_family == 'RedHat' else '/usr/bin/pg_config' }}"
      - --quiet
      - --yes
      - --wal-disk-size 8GB
  notify: Restart PostgreSQL
  when: is_timescale_loaded.stdout == "0"
