apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: internal
  namespace: internal-monitoring
spec:
  replicas: 2
  externalUrl: http://alertmanager.sof-k8s.storpool.net/
  clusterLabel: internal-am
  alertmanagerConfiguration:
    name: internal
    global:
      slackApiUrl:
        key: url
        name: "{{ slack_api_url_secret }}"
    templates:
      - configMap:
          key: slack.tmpl
          name: alertmanager-templates
