promscale_postgres_username: "promscale"
promscale_postgres_database: "promscale"

postgres_username: "{{ promscale_postgres_username }}"
postgres_password: "{{ promscale_postgres_password }}"
postgres_database: "{{ promscale_postgres_database }}"

prometheus_storage_retention: 1ms

prometheus_global:
  scrape_interval: 3s
  evaluation_interval: 15s

prometheus_remote_write:
  - url: "http://localhost:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_samples_per_send: 3000
      batch_send_deadline: 10s
      min_shards: 4
      max_shards: 200
      min_backoff: 100ms
      max_backoff: 10s

prometheus_remote_read:
  - url: "http://localhost:9201/read"
    read_recent: true

prometheus_scrape_configs: "{{ lookup('template', playbook_dir + '/prometheus/jobs.yaml') | from_yaml }}"

prometheus_alertmanager_config:
  - static_configs:
      - targets:
          - "{{ ansible_fqdn }}:{{ alertmanager_web_listen_port }}"

prometheus_alert_rules: []
prometheus_external_labels:
  grafana_url: "http://{{ ansible_fqdn }}"
