promscale_postgres_username: "promscale"
promscale_postgres_database: "promscale"

postgres_username: "{{ promscale_postgres_username }}"
postgres_password: "{{ promscale_postgres_password }}"
postgres_database: "{{ promscale_postgres_database }}"

prometheus_storage_retention: 12h

prometheus_global:
  scrape_interval: 3s
  evaluation_interval: 15s

prometheus_remote_write:
  - name: victoriametrics
    url: http://awx.sof-vm.storpool.local:31689/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

prometheus_scrape_configs: "{{ lookup('template', playbook_dir + '/prometheus/jobs.yaml') | from_yaml }}"

prometheus_alertmanager_config:
  - static_configs:
      - targets:
          - "{{ ansible_fqdn }}:{{ alertmanager_web_listen_port }}"

prometheus_alert_rules: []
prometheus_external_labels:
  grafana_url: "https://inframon.storpool.com"
