promscale_postgres_username: "promscale"
promscale_postgres_database: "promscale"

postgres_username: "{{ promscale_postgres_username }}"
postgres_password: "{{ promscale_postgres_password }}"
postgres_database: "{{ promscale_postgres_database }}"

prometheus_version: 2.28.1

prometheus_global:
  scrape_interval: 3s
  evaluation_interval: 15s

prometheus_remote_write:
  - url: "http://localhost:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_samples_per_send: 3000
      batch_send_deadline: 10s
      min_shards: 4
      max_shards: 200
      min_backoff: 100ms
      max_backoff: 10s

prometheus_remote_read:
  - url: "http://localhost:9201/read"
    read_recent: true

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node-exporter"
    honor_labels: true
    basic_auth:
      username: prometheus
      password: "{{ prometheus_secret }}"
    file_sd_configs:
      - files:
          - "/monitoring/file_sd/hosts_*.yaml"
  - job_name: "snmp"
    metrics_path: /snmp
    basic_auth:
      username: prometheus
      password: "{{ prometheus_secret }}"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: "{{ ansible_fqdn }}:9116"
    file_sd_configs:
      - files:
          - "/monitoring/file_sd/network_*.yaml"