prometheus_version: 2.28.1

prometheus_global:
  scrape_interval: 3s
  evaluation_interval: 15s

prometheus_remote_write:
  - url: "http://localhost:9201/write"
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_samples_per_send: 3000
      batch_send_deadline: 10s
      min_shards: 4
      max_shards: 200
      min_backoff: 100ms
      max_backoff: 10s

prometheus_remote_read:
  - url: "http://localhost:9201/read"
    read_recent: true

prometheus_scrape_jobs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "node-exporter-file-discovery"
    honor_labels: true
    file_sd_configs:
      - files:
          - "/monitoring/file_sd/dummy_load.yaml"
          - "/monitoring/file_sd/opennebula.yaml"