---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: ubuntu
    image: netcho/ubuntu-python3
    pre_build_image: true
  - name: centos-8
    image: centos:8
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    tty: True
    env:
      container: docker
provisioner:
  name: ansible
verifier:
  name: ansible
