---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: ubuntu
    image: netcho/ubuntu-python3
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
