---
- name: Installing missing locales on CentOS 8
  hosts: centos-8
  tasks:
    - name: Installing packages
      dnf:
        name:
          - langpacks-en
          - glibc-all-langpacks
        state: present