apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: bird-service
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  honorLabels: true
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/bird_service.yaml.j2') | from_yaml }}
