apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: bmc-metrics
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  honorLabels: true
  interval: 15s
  scrapeTimeout: 10s
  relabelConfigs:
    - sourceLabels: [ ipmi_module ]
      targetLabel: __param_module
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/bmcs.yaml.j2') | from_yaml }}
