apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: ipsec-exporter
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  interval: 15s
  relabelConfigs:
  - sourceLabels: [__address__]
    targetLabel: __param_target
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/ipsec_targets.yaml.j2') | from_yaml }}
