apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: ping-v4
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  path: /probe
  interval: 5s
  params:
    module: [ ping_v4 ]
  relabelConfigs:
    - sourceLabels: [ __address__ ]
      targetLabel: __param_target
    - targetLabel: __address__
      replacement: blackbox-exporter:9115
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/icmp.yaml.j2') | from_yaml }}
