apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: pmc-metrics
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/pcm_baremetal.yaml.j2') | from_yaml }}