apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: postgresql-service
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  honorLabels: true
  relabelConfigs:
    - sourceLabels: [ __address__ ]
      targetLabel: __address__
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/postgresql_service.yaml.j2') | from_yaml }}
