apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: power-devices
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  path: /snmp
  honorLabels: true
  interval: 30s
  scrapeTimeout: 29s
  relabelConfigs:
    - sourceLabels: [ snmp_mib ]
      targetLabel: __param_module
    - sourceLabels: [ __address__ ]
      targetLabel: __param_target
    - targetLabel: __address__
      replacement: snmp-exporter:9116
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/power_devices.yaml.j2') | from_yaml }}
