apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: ssh-service
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  metricsPath: /probe
  scrapeInterval: 5s
  params:
    module: [ ssh_banner ]
  relabelings:
    - sourceLabels: [ __address__ ]
      targetLabel: __param_target
      regex: '([^:]+)(:[0-9]+)?'
      replacement: '${1}:22'
    - targetLabel: __address__
      replacement: blackbox-exporter:9115
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/ssh_service.yaml.j2') | from_yaml }}
