apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: ssh-service
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  path: /probe
  interval: 5s
  params:
    module: [ ssh_banner ]
  relabelConfigs:
    - sourceLabels: [ __address__ ]
      targetLabel: __param_target
      regex: '([^:]+)(:[0-9]+)?'
      replacement: '${1}:22'
    - targetLabel: __address__
      replacement: blackbox-exporter:9115
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/ssh_service.yaml.j2') | from_yaml }}
