apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: web-service
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  path: /probe
  interval: 5s
  params:
    module: [ http_2xx ]
  relabelConfigs:
    - sourceLabels: [ __address__ ]
      targetLabel: __param_target
    - targetLabel: __address__
      replacement: blackbox-exporter:9115
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/web_service.yaml.j2') | from_yaml }}
