apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: ssh-service
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  metricsPath: /probe
  scrapeInterval: 5s
  params:
    module: [ http_2xx ]
  relabelings:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - targetLabel: __address__
      replacement: blackbox-exporter:9115
  staticConfigs: {{ lookup('template', 'manifests/monitoring/targets/web_service.yaml.j2') | from_yaml }}
