apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vmsingle-metrics-scrape
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  endpoints:
    - honorLabels: true
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: vmsingle
      app.kubernetes.io/instance: metrics
