apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: metrics
  namespace: internal-monitoring
spec:
  extraArgs:
    search.maxConcurrentRequests: '16'
  resources:
    limits:
      cpu: '2'
      memory: 5000Mi
  retentionPeriod: '12'
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1536Gi
    storageClassName: storpool-nvme-database
    volumeName: pvc-3c81dcaa-efe8-4f21-9aca-28066a874a92
