apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: metrics
  namespace: internal-monitoring
spec:
  extraArgs:
    search.maxConcurrentRequests: '16'
  removePvcAfterDelete: true
  resources:
    limits:
      cpu: '2'
      memory: 5000Mi
  retentionPeriod: '12'
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.97.1
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1536Gi
    storageClassName: storpool-nvme-database
