---
apiVersion: v1
kind: Service
metadata:
  name: ipmi-exporter
  labels:
    app.kubernetes.io/name: ipmi-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ipmi-exporter
  ports:
    - name: ipmi-scrape
      port: 9290
      targetPort: metrics
