---
# tasks file for promscale
- name: Creating Promscale user group
  group:
    name: promscale
    state: present

- name: Create Promscale user
  user:
    name: promscale
    groups:
      - promscale
    create_home: false
    shell: /bin/nologin

- name: Downloading Promscale
  get_url:
    url: "https://github.com/timescale/promscale/releases/download/{{ promscale_version }}/promscale_{{ promscale_version }}_Linux_x86_64"
    dest: /usr/bin/promscale
    mode: 0755
  notify: Restart Promscale

- name: Downloading Promscale systemd file
  get_url:
    url: "https://github.com/timescale/promscale/raw/master/build/systemd/promscale.service"
    dest: /etc/systemd/system/promscale.service
    mode: 0644
  notify: Reload systemd

- name: Generating Promscale systemd environment file
  template:
    dest: "{{ promscale_config_path }}"
    src: promscale.config.j2
    mode: 0644
  notify: Restart Promscale

- name: Editing Promscale unit service file
  replace:
    path: /etc/systemd/system/promscale.service
    regexp: "EnvironmentFile=__ENV_FILE__"
    replace: "EnvironmentFile={{ promscale_config_path }}"
  notify:
    - Reload systemd
    - Restart Promscale

- name: Creating Promscale maintenance service
  template:
    dest: /etc/systemd/system/promscale-exec-maintenance.service
    src: promscale-exec-maintenance.service.j2
    mode: 0644
  notify:
    - Reload systemd
    - Enable Promscale maintenance service

- name: Creating Promscale maintenance timer
  copy:
    dest: /etc/systemd/system/promscale-exec-maintenance.timer
    src: promscale-exec-maintenance.timer
    mode: 0644
  notify:
    - Reload systemd
    - Enable Promscale maintenance timer
