---
# tasks file for promscale
- name: Installing dependencies
  include_tasks: "install_dependencies/{{ ansible_distribution | lower }}.yml"

- name: Creating Promscale user group
  group:
    name: promscale
    state: present

- name: Create Promscale user
  user:
    name: promscale
    groups:
      - promscale
    create_home: false
    shell: /bin/nologin

- name: Downloading Promscale
  get_url:
    url: "https://github.com/timescale/promscale/releases/download/{{ promscale_version }}/promscale_{{ promscale_version }}_Linux_x86_64"
    dest: /usr/bin/promscale
    mode: 0755
  notify: Restart Promscale

- name: Downloading Promscale systemd file
  get_url:
    url: "https://github.com/timescale/promscale/raw/master/build/systemd/promscale.service"
    dest: /etc/systemd/system/promscale.service
    mode: 0644
  notify: Reload systemd

- name: Generating Promscale user password
  set_fact:
    promscale_user_password: "{{ promscale_password if promscale_password is defined else lookup('password', '/dev/null chars=ascii_lowercase,digits length=16') }}"

- name: Creating Promscale PostgreSQL database
  become_method: sudo
  become_user: postgres
  become: true
  community.postgresql.postgresql_db:
    name: "{{ promscale_database_name }}"

- name: Creating Promscale PostgreSQL user
  become_method: sudo
  become_user: postgres
  become: true
  community.postgresql.postgresql_user:
    name: "{{ promscale_username }}"
    password: "{{ promscale_user_password }}"
    db: "{{ promscale_database_name }}"
    priv: ALL

- name: Generating Promscale systemd environment file
  template:
    dest: "{{ promscale_config_path }}"
    src: promscale.config.j2
    mode: 0644
  notify: Restart Promscale

- name: Editing Promscale unit service file
  replace:
    path: /etc/systemd/system/promscale.service
    regexp: "EnvironmentFile=__ENV_FILE__"
    replace: "EnvironmentFile={{ promscale_config_path }}"
  notify:
    - Reload systemd
    - Restart Promscale
