apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: jenkins
  namespace: internal-monitoring
  labels:
    storpool.com/env: production
spec:
  honorLabels: true
  path: /prometheus
  staticConfigs:
    - targets:
      - jenkins.storpool.net
      labels:
        instance: jenkins
        type: virtual-machine
        location: mars
        environment: production

