---
- name: Generating file_sd configutaion files
  become: true
  template:
    dest: "{{ file_sd_base_path }}/{{ filename }}.yaml"
    src: "{{ filename }}.yaml.j2"
    owner: root
    group: prometheus
    mode: 0640
  loop: "{{ lookup('fileglob', file_sd_template_path) }}"
  loop_control:
    loop_var: filename
  notify: Reloading Prometheus
