---
- name: Debugging file templates
  debug:
    msg: "{{ lookup('fileglob', file_sd_template_path) }}"
    verbosity: 2

- name: Debugging DNS FQDN lookups
  debug:
    msg: "Host FQDN {{ ansible_fqdn }} resolves to IP {{ lookup('dig', hostvars[host]['ansible_fqdn']) | first }}"
    verbosity: 2

- name: Generating file_sd configutaion files
  become: true
  template:
    dest: "{{ file_sd_base_path }}/{{ template | basename | splitext | first }}"
    src: "{{ template }}"
    owner: root
    group: prometheus
    mode: 0640
  loop: "{{ lookup('fileglob', file_sd_template_path) | split(',') }}"
  loop_control:
    loop_var: template
  notify: Reloading Prometheus
